### PR TITLE
Added custom url input field, show source button more examples in the cheat sheet

### PR DESCRIPTION
**Pull request by DanielFlamino**
Added a submenu to the markdown toolbar where the url for the link can be inserted, instead of using the browser's javascript input prompt.

Added three more examples to the markdown cheat sheet (unordered list, ordered list and horizontal rule)

Added a show source button beneath discussions and comments, so that users can see the markdown that was used instead of the finished html result

### CODE REVIEW

**Comment by whoaverse** [comment]
Thank you for the explanation. If I understood correctly, this is basically the same as the edit button. If so, I don't think the button should appear for users own submissions while the user is logged in (to minimize cluttering). Do you agree?

**Comment by DanielFlamino** [comment]
Never thought about that, since RES keeps the "source" link there even if you made the comment (like on the Gfycat I posted above, which was a comment of mine).

**Comment by DanielFlamino** [comment]
Wait... Why did I put it to display only if the user is the author? o_O

**Comment by whoaverse** [comment]
No worries :)

"Aesthetic and minimalist design" - one of the 10 Jacob Nielsen heuristics: "Dialogues should not contain information which is irrelevant or rarely needed. Every extra unit of information in a dialogue competes with the relevant units of information and diminishes their relative visibility."

If you can, try to edit it so that the source button is only visible if the user is not the author (or not logged in). If not, I'll modify it tomorrow :)

**Comment by DanielFlamino** [comment]
[I still have no clue why I put it to display only if you were the author, though.](http://i.imgur.com/O2oQYeN.jpg)

**Comment by DanielFlamino** [comment]
Now I noticed that you wrote if a person is not logged in. But in that case, why should the person care to see the source for the comment? If they are not logged in, they aren't going to comment, so they probably don't care about learning the markdown. If they were that much interested, one would expect that they would be already logged in, no?

**Comment by whoaverse** [comment]
You're right, let's just make it visible to logged in, non-author users.

**Comment by DanielFlamino** [comment]
welp... then it is done, I guess,

**Comment by whoaverse** [comment]
I just tested this and I get this JavaScript error when I click the source button:

"TypeError: $(...).find(...)[0].slideToggle is not a function"

**Comment by DanielFlamino** [comment]
It should be fixed on the pull request I sent
http://i.imgur.com/iq4cotU.png

**Pull request merged**
